In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
import numpy as np
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(a[2,2])

9


In [5]:
#SLICING
print(a[0:2,[0,2]])

[[1 3]
 [4 6]]


In [6]:
print("data type " + str(a.dtype))
print("Item size " + str(a.itemsize))
print("Size " + str(a.size))
print("dimension " + str(a.ndim))

data type int32
Item size 4
Size 9
dimension 2


In [7]:
print(np.linspace(1, 10, 10))
#                STRT END TOTAL VALUES REQUIRED

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [8]:
print("max value " + str(a.max()))

max value 9


In [9]:
print("min value " + str(a.min()))

min value 1


In [10]:
print("sum of total array " + str(a.sum()))

sum of total array 45


In [11]:
#PRINT SUM OF THE ARRAY COLUMNWISE
print("sum of total array " + str(a.sum(axis = 0)))

sum of total array [12 15 18]


In [12]:
#PRINT SUM OF THE ARRAY ROWWISE
print("sum of total array " + str(a.sum(axis = 1)))

sum of total array [ 6 15 24]


In [13]:
#PRINT SQUARE ROOT OF THE ARRAY 
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [14]:
#PRINT STANDARD DEVIATION OF THE ARRAY 
print(np.std(a))

2.581988897471611


In [15]:
b = np.array([1,2,3])
print(a + b)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [16]:
print(a - b)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [17]:
print(a * b)

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [18]:
print ( a / b)

[[1.  1.  1. ]
 [4.  2.5 2. ]
 [7.  4.  3. ]]


In [22]:
#CONCATINATING 2 ARRAYS VERTICALLY
print(np.vstack([a,b]))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


In [23]:
#CONCATINATING 2 ARRAYS HORIZONTLY
print(np.hstack([a,b]))

ValueError: all the input arrays must have same number of dimensions

In [28]:
b = np.array([(10,11,12), (13,14,15), (16,17,18)])
#CONCATINATING 2 ARRAYS HORIZONTLY
print(np.hstack([a,b]))

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
